Repository noahallen/Avalon, pull requests merged in 2024-02, with the labels that each got.

#26 Added custom toggles and added some initial ones to the feature-selec…
  src/App.css
  src/App.js
  src/components/ToggleSlider.js
  src/pages/FeatureSelectionPage.jsx
  src/style/Toggleslider.css
  style/csshere.txt
Labels: Client UI, Client Business Logic, Development

#27 Added userNameInput component and some minor enhancements
  src/App.css
  src/components/box-join.js
  src/components/sampleAuth.js
  src/components/userNameInputBox.js
  src/index.css
  src/pages/RoomCreationPage.jsx
Labels: Client UI, Development

#29 Noah backend waiting room +create/join workflows
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/GameProvider.js
  src/components/QRCode.js
  src/components/userNameInputBox.js
  src/firebase/api.jsx
  src/pages/EnterName.jsx
  src/pages/RoomCreationPage.jsx
  src/pages/TestStatePage.jsx
  src/pages/WaitingRoom.jsx
  src/res/Gear.png
  src/res/ImagesGohere.txt
Labels: Client Business Logic, Development

#30 create intermediate page for QR code to redirect with gameid and iscr…
  src/components/box-join.js
  src/components/userNameInputBox.js
  src/pages/EnterName.jsx
  src/pages/JoinIntermediate.jsx
  src/routes/index.js
Labels: Client Business Logic

#31 Added the ability to create and join a game and wait in the waiting room
  src/components/box-join.js
  src/components/userNameInputBox.js
  src/pages/EnterName.jsx
  src/pages/JoinIntermediate.jsx
  src/routes/index.js
Labels: Client Business Logic, Development

#36 Add role assignment API hook for database
  build/manifest.json
  package.json
  src/firebase/api.jsx
  src/hooks/samplehook.txt
  src/pages/WaitingRoom.jsx
Labels: Client Database Layer, Development

#34 Background/css
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/AvalonHeader.js
  src/index.css
  src/pages/RoomCreationPage.jsx
  src/pages/WaitingRoom.jsx
  src/res/Castle.png
  src/res/Scroll.png
  src/res/Wall.png
Labels: Client UI, Development
