Repository noahallen/Avalon, pull requests merged in 2024-01, with the labels that each got.

#18 Create game context
  .prettierrc
  .vscode/settings.json
  Avalon.code-workspace
  README.md
  firebase/api.jsx
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  src/App.css
  src/App.js
  src/App.test.js
  src/components/GameProvider.js
  src/components/components.txt
  src/index.css
  src/index.js
  src/pages/HomePage.jsx
  src/pages/NotFound.jsx
  src/reportWebVitals.js
  src/routes/index.js
  src/setupTests.js
Labels: Client Business Logic

#20 Add more state management hooks to GameProvider
  src/App.js
  src/App.test.js
  src/components/GameProvider.js
  src/index.js
  src/pages/HomePage.jsx
  src/pages/TestStatePage.jsx
  src/routes/index.js
Labels: Client Business Logic, Development

#22 Create Frontend Components and Template Pages
  src/App.js
  src/components/box-join.js
  src/index.css
  src/pages/FeatureSelectionPage.jsx
  src/pages/HomePage.jsx
  src/pages/RoleSelectionPage.jsx
  src/pages/RoomCreationPage.jsx
  src/routes/index.js
Labels: Client UI, Development

#25 Combined new DB approach with our old test state page
  src/App.test.js
  src/components/GameProvider.js
  src/firebase/api.jsx
  src/pages/HomePage.jsx
  src/pages/RoleSelectionPage.jsx
  src/pages/TestStatePage.jsx
  src/routes/index.js
Labels: Client Business Logic, Client Database Layer, Development
